{% set name = "bpython" %}
{% set version = "0.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c246fc909ef6dcc26e9d8cb4615b0e6b1613f3543d12269b19ffd0782166c65b

build:
  number: 1
  entry_points:
    - bpython = bpython.curtsies:main
    - bpython-urwid = bpython.urwid:main
    - bpdb = bpdb:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]
  skip: true  # [win]
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

    - curtsies >=0.4
    - cwcwidth
    - greenlet
    - pygments
    - pyxdg
    - requests
    - typing_extensions  # [py<311]

    # see https://github.com/bpython/bpython/issues/1043
    - urwid <3.0  # [unix and py<314]
    - watchdog

test:
  imports:
    - bpython
    - bpython.curtsiesfrontend
    - bpython.test
    - bpython.test.fodder
    - bpython.translations
    - bpdb
  commands:
    - bpython --help
    - bpython-urwid --help  # [unix and py<314]
    - bpdb --help

about:
  home: http://www.bpython-interpreter.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fancy Interface to the Python Interpreter
  dev_url: https://github.com/bpython/bpython

extra:
  recipe-maintainers:
    - holymonson
    - mariusvniekerk
    - scopatz
