build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
travis:
  secure:
    BINSTAR_TOKEN: tjlvF79/XY6vme+qQHWDS2xWWJ/V8sA79cQipZQGtpfVt2cqgVQ9nYQsbdfahBJIPrs8lvOD1Caf1U/d0yeYz5xIkRhcDUAz7UWBomwV0aGrr3uk607TuhybmvZfLJ1Z0iumUyK+Q2TAfwyRrS4xviM5+dkvgJwpXqcxr1b5VvFBMs5/c6IHAXZPSYDOCEm2E+QL/R2GL0+Yd6zEmu3aq+GZCsa8WqCdHdxfoLi9hw6qek75QvJPThrQabnalb7BgBp/3sj6N4EjpJfCvKKieYjyfIhGjVyc7rHhQa4jGGZQem7BlKQmBZqNxAXA9Ip0pHjlDE/Z68ybS3O238lqeqe1H1XVU60xy68ymlbcRBwko7v07lEiCMQ4c+tWgbmRdsyv6KaYu5GYeHOUPpwgrkW2owZyQ2RyowATDoTeszskOEa9eSuftXXR81MKEL5PkORY7HdCbn6FnL7mj9NFsArMB4frTm8+julTAO7YnbX8j01xraLeYsouhfiHMvD9nm6lw51ZbOk7aU8F56PlBYR0rj1/UKfOhCZVYmNIVjUr3Z0OOu2JXbN2daW3JeCFch6Efh4LZwif/pKAEDIYQTrtHgWOzCcedN6kgIY9m0VqUWm+UfW2L/lCwD9sDWV/t8Vjf0ylTlb1VYbR8ssiAdIMgAAUmgkFeb0kCO1OSvA=
